### ISSUE TITLE
Version Control Sync is Paid or Unpaid?

### ISSUE THREAD

**Issue by SethFalco** [Kong/insomnia-docs#105]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

https://docs.insomnia.rest/insomnia/version-control-sync

### What part(s) of the article would you like to see updated?

It states that this is a paid feature, however I have never paid for Insomnia (through I did signup for the free-trial before) but have access to this feature.

This means there is either a bug in Insomnia, or the docs are outdated and this is a free feature?

Or perhaps a paid subscription is required to enable syncing, but once enabled it can be used for free for that collection?

Could you bring some clarity to the documentation? Or if this is a bug, let me know and I'll open a bug report in the main repository.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by filfreire** [comment]
Hi @SethFalco we're following up on this issue internally, thank you for the heads up!
