### ISSUE TITLE
Suggestion to history recovery doesn't work on mac

### ISSUE THREAD

**Issue by jask-vmi** [Kong/insomnia-docs#125]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

   Logs location

### What part(s) of the article would you like to see updated?

Macs recovery logs location

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by wongstein** [comment]
@jask-vmi please be more specific with what the issues are in the Docs and what would help.  It's not clear to me what you are looking for.
