### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by f34ther** [Kong/insomnia-docs#130]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

https://docs.insomnia.rest/insomnia/password-recovery

### What part(s) of the article would you like to see updated?

To do this, launch Insomnia, navigate to Settings > Account, and click on Change Password. > upon following instructions, only two options are provided in the desktop app: 1. view plans (aka, pay money) or 2. log in. there is no option for change password.

### Additional information

![Screenshot (24)](https://user-images.githubusercontent.com/110642857/214187916-79fdee89-cb73-4672-bfc5-f33cab5bbc7b.png)

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by filfreire** [comment]
@f34ther this will be improved in the near future, and we'll eliminate the need to contact support in order to recover/reset password.
