### ISSUE TITLE
Error doing action Initializing GIT repository failed.

### ISSUE THREAD

**Issue by bkolo** [Kong/insomnia-docs#137]
i have a repo and sucessfully synced  my workspace however the second user who I am trying to sync/share this with is getting the following error
Error doing action
Initializing GIT repository failed. Please delete the project folder: C:\...\AppData\Roaming\Insomnia\plugins\insomnia-plugin-git-sync\git\wrk_f7684ec8f08541999034b26ee478f9f5
we have deleted the folder several times only to repeat the same error

**Comment by filfreire** [comment]
@bkolo thanks for reporting this, we don't maintain the plugin you are attempting to use, it's a community plugin.

If you are using regular git sync and have an issue, please report it in https://github.com/Kong/insomnia/issues
