### ISSUE TITLE
While using variables to store data. Variable load time delay

### ISSUE THREAD

**Issue by davinsrma** [Kong/insomnia-docs#138]
For my live project. i am using lots of variables. The value of those variables I am taking from response of any API. 
But to load those variables insominia is taking very long time.

It happened approx one or two months before. I thaught this may a temporery issue. It will get fix in next update. But this issue is still exists.

**Comment by filfreire** [comment]
@davinsrma thanks for reporting. This kind of performance issue is know. We're tracking all performance issues here: https://github.com/Kong/insomnia/labels/B-performance
