### ISSUE TITLE
The application data location is incorrect for Windows

### ISSUE THREAD

**Issue by jehugaleahsa** [Kong/insomnia-docs#142]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

https://docs.insomnia.rest/insomnia/application-data

### What part(s) of the article would you like to see updated?

This claims that there is a folder directly under `%APPDATA%` called `Insomnia`. But it will always be split up by `Local`, `LocalLow`, and `Roaming`. Then there will be sub-directories under those yet, so it's not clear where the application data actually lives.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by victorgonzalezz** [comment]
### Insomnia 426 Upgrade Required

When testing the route in .get() I got this answer. I used another app and it returned 200. Would Insomnia itself give me this error? Has anyone come across this situation?
