### ISSUE TITLE
How to reset if I forgot my password?

### ISSUE THREAD

**Issue by Realistic3D** [Kong/insomnia-docs#144]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

It's literally shameful to see only useless information on recovering password link

![image](https://github.com/Kong/insomnia-docs/assets/119076217/aef90eab-459e-469b-bf13-21a45c346ff8)
![image](https://github.com/Kong/insomnia-docs/assets/119076217/81fe8a05-fa87-4486-a92b-010d55550202)

What is that and how to fix it?

### What part(s) of the article would you like to see updated?

recovering password

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/5978
