### ISSUE TITLE
Cannot recover password on web page

### ISSUE THREAD

**Issue by RebelionTheGrey** [Kong/insomnia-docs#151]
Guys, on your login page when you click on "Recover password" you get a redirection on Troubleshooting page with just an information, but not any functionality for password recovering...

**Comment by gallegosdamian505** [comment]
.

**Comment by mostarrcoding** [comment]
Bump & seconded.

**Comment by ansq62** [comment]
So there's just no way to recover an Insomnia account if a user loses their password? There's a fine balance between security and user experience... seems like a pretty over-the-top intentional security decision.

**Comment by aristidesquetajr** [comment]
I'm facing the same problem and my backup is on my old computer, I no longer have access to it

**Comment by jeanbort** [comment]
I have the same problem. How reset the password when you lose it.

**Comment by filfreire** [comment]
Hey folks, what @dan-ville mentioned above is the case. https://github.com/Kong/insomnia-docs/issues/151#issuecomment-1679030322


You can login using "Continue with Email" https://app.insomnia.rest/app/authorize - and then in the settings delete your account and recreate a new one.

Keep in mind you'll lose any data you had in your personal project, but you can be reinvited to any teams/organizations by Admins or Owners of those teams.
