### ISSUE TITLE
output global flag not working for inso run test cli

### ISSUE THREAD

**Issue by rmacontributor** [Kong/insomnia-docs#156]
Hi,

I'm currently trying to test cli. We want to generate a report and store into the file in order to archive our run in a safe place.
To achieve that we plan to use the --output global flag as describe here : 
https://docs.insomnia.rest/inso-cli/cli-command-reference/inso-run-test

```
inso run test --verbose "example-xsd" --env "acc" --src ./example.json  --reporter min --output .
error: unknown option '--output'
```

```
inso run test --verbose "example-xsd" --env "acc" --src ./example.json  --reporter min -o .
error: unknown option '-o'
```

Is it correct use of the cli ?

Thanks for your help, 

Kr,

**Comment by filfreire** [comment]
@rmacontributor thanks for reporting this. The `--output` flag doesn't apply to `inso run test` - fixing the documentation in #166
