### ISSUE TITLE
%APPDATA% already includes the Roaming directory

### ISSUE THREAD

**Issue by faustool** [Kong/insomnia-docs#159]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

https://docs.insomnia.rest/insomnia/application-data

### What part(s) of the article would you like to see updated?

This bullet takes the reader to a non-existing directory:
* `%APPDATA%\Roaming\Insomnia` on **Windows**

And that is because the `%APPDATA%` variable already includes the `Roaming` directory:

```batch
C:\Users\someuser>echo %APPDATA%
C:\Users\someuser\AppData\Roaming
```

See more at [Variables that are recognized only in the user context](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables#variables-that-are-recognized-only-in-the-user-context):

| Variable        | Explanation                                                                                                                                          |
|-----------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| _APPDATA_       | Same as **CSIDL_APPDATA**.                                                                                                                           |
| _CSIDL_APPDATA_ | The file-system directory that serves as a common repository for application-specific data. A typical path is `C:\Users\<username>\AppData\Roaming`. |

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by nrekretep** [comment]
These parts of the documentation should also be updated:

* https://docs.insomnia.rest/insomnia/faq#where-does-the-application-store-data
* https://docs.insomnia.rest/insomnia/faq#where-does-the-application-store-logs

**Comment by filfreire** [comment]
Fixed with https://github.com/Kong/insomnia-docs/pull/152
