### ISSUE TITLE
Link to change password not found

### ISSUE THREAD

**Issue by gifagundes** [Kong/insomnia-docs#161]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

https://docs.insomnia.rest/insomnia/change-password

### What part(s) of the article would you like to see updated?

https://app.insomnia.rest/app/account/

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by clintonmedbery** [comment]
I don't know why this is not getting more attention. I cannot log into my account or use the app. I guess I am going to have to use postman.
