### ISSUE TITLE
CA Certificate doesn't worked

### ISSUE THREAD

**Issue by MrRanjanRavi** [Kong/insomnia-docs#187]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

I added the network proxy as localhost:PortNumber and set up the same for the other proxy listener tool. Then, I added the CA certificate to the connection settings under the work scratchpad. However, it didn’t work and I’m getting an ‘Error: SSL connect error’. I’m able to proxy to HTTP connections, but HTTPS doesn’t work.
![image](https://github.com/Kong/insomnia-docs/assets/156108774/b6f2b9ef-946d-4c60-9d5d-5578048f7c33)
![image](https://github.com/Kong/insomnia-docs/assets/156108774/5a0a61c5-4058-48ca-9857-1964e8a377bf)

### What part(s) of the article would you like to see updated?

Insomina should be allowed to be configured with other proxy tools like the Postman tool.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by filfreire** [comment]
@MrRanjanRavi please report this in https://github.com/Kong/insomnia/ instead if it is still affecting you in the latest Insomnia version.
