### ISSUE TITLE
Generate Client Code do not works.

### ISSUE THREAD

**Issue by mastro-star** [Kong/insomnia-docs#214]
Hello, I've click on Generate Code but no results had

<img width="771" alt="Screenshot 2024-06-28 alle 12 21 55" src="https://github.com/Kong/insomnia-docs/assets/174107133/ba878a1f-2959-4cba-8ea4-4126b7b8c5dd">

**Comment by filfreire** [comment]
@mastro-star please report this if you are still facing it in the correct repository: https://github.com/Kong/insomnia

**Comment by mastro-star** [comment]
With last insomnia version problem is solved, many many thanks!
