### ISSUE TITLE
Bug: Project's folders structure isn't works. 

### ISSUE THREAD

**Issue by yaroslavolekh** [Kong/insomnia-docs#215]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

It's impossible to use expand/collapse folders of requests (by cllicking on the folder's ttitle).

Version: Insomnia 9.3.1
Build date: 6/28/2024
OS: Darwin x64 23.5.0
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

### What part(s) of the article would you like to see updated?

Folders has to expand/collapse by by cllicking on the folder's ttitle

### Additional information

https://monosnap.com/file/SHmFWkn9PCBvlnSub5LEhkypu3YZaO

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by bernardohmr** [comment]
same here. annoying!

**Comment by filfreire** [comment]
fixed in 9.3.2
