### ISSUE TITLE
Missing Folder Environments

### ISSUE THREAD

**Issue by hebertlima** [Kong/insomnia-docs#218]
Where did the environment [variables for the folder](https://docs.insomnia.rest/insomnia/environment-variables#folder-environments) go?

![image](https://github.com/Kong/insomnia-docs/assets/34013325/fdd39a96-a1b7-494a-841d-2cbd0647807c)

**Comment by antobrines** [comment]
In their documentation, it says that it is rarely used, so they may have simply removed it. This is a real shame because I used it a lot. If there are any other alternatives, that would be great.

**Comment by kaufmed** [comment]
They moved it. You click on the folder itself and it pops up tabs in the main window.
