### ISSUE TITLE
Preview issue between 'Mac, windows, and Linux' + Purple Anchor?

### ISSUE THREAD

**Issue by SilentReptar** [Kong/insomnia-docs#97]
### Code of Conduct

- [X] I have read and agree to the Insomnia Docs project's [Code of Conduct](https://github.com/Kong/insomnia-docs/blob/main/CODE_OF_CONDUCT.md).

### What article on docs.insomnia.rest is affected?

https://docs.insomnia.rest/inso-cli/install
The buttons to switch between the preview code to install for mac, windows, and linux doesn't work.
Also I'm not sure what the purple anchors do but I accidentally clicked on the first sub header.

### What part(s) of the article would you like to see updated?

The switching between previews of Mac, Windows, and Linux working (as it is stuck on Mac, and I want to see how to install this on windows). 

Cheers

### Additional information

Edit: Preview to change between 'Mac, Windows, Linux' doesn't work on my Firefox browser, but does work on Microsoft Edge. Also still not sure what the purple anchors do, I fear as this open source that I may have stuffed something up.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by filfreire** [comment]
Hi @SilentReptar thank you for reporting this.

Can you confirm what is the operative system and browser (and its version) you are using? 
Are you using any kind of screen reader, adblock or noscript browser extensions (or similar)?

Just so it's clear, you basically are not getting the page to behave in like it does on this GIF:

![Kapture 2022-04-26 at 09 53 41](https://user-images.githubusercontent.com/11976836/165262291-cef69fb8-623c-4822-8a7d-0a58ed45d206.gif)

**Comment by SilentReptar** [comment]
Hi @filfreire the operating system I am using is windows 11, browser I used (that the preview didn't work on) is Firefox 99.0.1 (64-bit) - works however on Microsoft Edge Version 100.0.1185.50 (Official build) (64-bit). I am using an adblocker called Privacy Badger on Firefox though if that has any effect?

And yes that's correct, was having trouble with the page responding as your GIF with Firefox (is the one with the ad blocker). 
Also I had a query about the purple anchors as I'm not sure what they do? 
Cheers

**Comment by filfreire** [comment]
Hi @SilentReptar sorry for not getting back to this sooner.

It is possible that the adblocker could cause this. I haven't noted this kind of behavior with ublock origin

One you click on one of purple anchors it serves to link sections of the HTML doc - https://www.geeksforgeeks.org/how-to-create-links-to-sections-within-the-same-page-in-html/
